### ISSUE TITLE
Nexys SerWB example not building

### ISSUE THREAD

**Issue by rlipperts** [enjoy-digital/liteiclink#2]
While trying to use LiteICLink in my own design I encountered the following error:

```AttributeError: 'SERDESTestSoC' object has no attribute 'add_cpu_or_bridge'```

When I checked the original nexys example I encountered the same error. I've built it with the following command:

```./nexys.py serwb```

After beginning the build process it ran into the following error:

```
Traceback (most recent call last):
  File "./nexys.py", line 232, in <module>
    main()
  File "./nexys.py", line 223, in main
    soc = SERDESTestSoC(platform)
  File "./nexys.py", line 129, in __init__
    BaseSoC.__init__(self, platform)
  File "./nexys.py", line 109, in __init__
    self.add_cpu_or_bridge(UARTWishboneBridge(platform.request("serial"),
  File "/home/rlipperts/tools/litex-repos/migen/migen/fhdl/module.py", line 136, in __getattr__
    raise AttributeError("'"+self.__class__.__name__+"' object has no attribute '"+name+"'")
AttributeError: 'SERDESTestSoC' object has no attribute 'add_cpu_or_bridge'
```

Is the error on my side (missing some arguments at execution or something along these lines) or is the example not up-to-date?

**Comment by enjoy-digital** [comment]
@rlipperts: thanks for the feedback, the example needs to be updated, i'm planning to work on this in the next days since will use SerWB on design.

**Comment by rlipperts** [comment]
Any progress so far?

**Comment by enjoy-digital** [comment]
@rlipperts: i just updated the design with https://github.com/enjoy-digital/liteiclink/commit/63987bf4e2d680518eb2e15aafe46163bc7f7b92 and verified the link is initialized correctly. I'll spend more time on this in the next weeks to improve the code and examples.

**Comment by enjoy-digital** [comment]
@rlipperts: this has been updated. 

You can build and load the example design with::
`./nexys_video.py --low-speed --build --load`

Initialize LiteX Server with:
`litex_server --uart --uart-port=/dev/ttyUSBX` to open LiteX Server.

Initialize SerWB link and test access to the SRAM (through SerWB) with:
`./test_serwb.py --ident --init --sram`
